name: nodiview
base: core22
version: git
summary: Modern Linux image viewer with optimization capabilities
description: |
  nodiView is a feature-rich image viewer built with GTK4 and Libadwaita,
  providing a modern interface for viewing, editing, and optimizing images.

  Features:
  - Image viewing with zoom controls and fullscreen mode
  - Side-by-side comparison of original and optimized images
  - Image optimization for JPEG, PNG, GIF formats
  - Batch operations for multiple images
  - Basic editing: rotation, mirroring, cropping
  - Format conversion between different image types
  - Multilingual support (EN, DE, ES, FR, UK)

grade: stable
confinement: strict

apps:
  nodiview:
    command: usr/bin/python3 $SNAP/bin/nodiview
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - removable-media
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0:$SNAP/usr/lib/girepository-1.0

parts:
  nodiview:
    plugin: python
    source: .
    build-packages:
      - python3-dev
      - python3-gi
      - python3-gi-cairo
      - libgirepository1.0-dev
      - libvips-dev
      - pkg-config
      - libcairo2-dev
      - libglib2.0-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libvips42
      - libgirepository-1.0-1
      - libcairo2
      - libglib2.0-0
    override-build: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL Pillow pyvips
