name: nodiview
version: '0.1.0'
summary: Ein moderner Linux-Bildbetrachter mit integrierter Bildoptimierung
description: |
  nodiView ist ein moderner, schlanker Bildbetrachter für Linux, der die 
  Kern-Funktionalitäten von IrfanView mit den Optimierungs-Features von RIOT kombiniert.
  
  Features:
  - Unterstützung für gängige Bildformate
  - Zoom und Navigation
  - Grundlegende Bearbeitung (Rotation, Spiegeln, Zuschneiden)
  - Bildoptimierung (JPEG, PNG, GIF)
  - Batch-Konvertierung und -Optimierung

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
    run-on: [amd64, arm64]
  - build-on: arm64
    run-on: [arm64]

apps:
  nodiview:
    command: nodiview
    desktop: usr/share/applications/nodiview.desktop
    plugs:
      - home
      - removable-media
      - x11
      - wayland
      - opengl
      - network

parts:
  nodiview:
    plugin: python
    source: .
    python-packages:
      - requirements.txt
    build-packages:
      - python3-dev
      - python3-pip
      - libvips-dev
      - libgirepository1.0-dev
      - gcc
      - pkg-config
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
    stage-packages:
      - python3
      - python3-gi
      - python3-pil
      - libvips
      - libgirepository-1.0-1
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libcairo2
      - libgdk-pixbuf2.0-0
      - shared-mime-info
    organize:
      data/*: usr/share/nodiview/data/
    prime:
      - -usr/lib/python3*/dist-packages/*.pyc
      - -usr/lib/python3*/dist-packages/*.pyo

